export const images = {
  0: require("@/assets/Robotics Theory.jpeg"),
  1: require("@/assets/Basic ROS2.jpeg"),
  2: require("@/assets/ROS Basics.jpeg"),
  3: require("@/assets/Intermediate ROS2.jpeg"),
  4: require("@/assets/Robotics Theory.jpeg"),
  5: require("@/assets/Navigation ROS2.jpeg"),
  6: require("@/assets/Manipulation.jpeg"),
  7: require("@/assets/Robot Creation.jpeg"),
  8: require("@/assets/AI.jpeg"),
  9: require("@/assets/ROS DEBUGGING.jpeg"),
  10: require("@/assets/Course of Product.jpeg"),
  11: require("@/assets/Web Devel FTR Robots.jpeg"),
  12: require("@/assets/Simulation.jpeg"),
  13: require("@/assets/Enterprise.jpeg"),
};

export const nodes = [
  { id: 0, name: "0. Foundations", main: true },
  { id: 1, name: "1. Basic ROS2", main: true },
  { id: 2, name: "2. ROS Basics", main: true },
  { id: 3, name: "3. Intermediate ROS2", main: true },
  { id: 4, name: "4. Robotics Theory", main: true },
  { id: 5, name: "5. Navigation ROS2", main: true },
  { id: 6, name: "7. Manipulation", main: true },
  { id: 7, name: "8. Robot Creation", main: true },
  { id: 8, name: "9. Artificial Intelligence", main: true },
  { id: 9, name: "10. ROS Debugging", main: true },
  { id: 10, name: "11. Course of Product", main: true },
  { id: 11, name: "12. Web Devel for Robots", main: true },
  { id: 12, name: "13. Simulation", main: true },
  { id: 13, name: "14. Enterprise", main: true },
  { id: 14, name: "Python3 for Robots", main: false },
  { id: 15, name: "Linux for Robotics", main: false },
  { id: 16, name: "C++ Basics for Robotics", main: false },
  { id: 17, name: "Gazebo Sim with ROS2", main: false },
  { id: 18, name: "TF in ROS2", main: false },
  { id: 19, name: "URDF Robot Modelling ROS2", main: false },
  { id: 20, name: "ROS2 Basics in 3 Days (Rust)", main: false },
  { id: 21, name: "ROS2 Basics in 5 Days (Python)", main: false },
  { id: 22, name: "ROS2 Basics in 5 Days (C++)", main: false },
  { id: 23, name: "ROS2 Security", main: false },
  { id: 24, name: "ROS1-ROS2 Migration", main: false },
  { id: 25, name: "Behavior Trees for ROS2", main: false },
  { id: 26, name: "Advanced Modern C++ for robotics", main: false },
  { id: 27, name: "Intermediate ROS2 (Python)", main: false },
  { id: 28, name: "Intermediate ROS2 (C++)", main: false },
  { id: 29, name: "ROS2 Control", main: false },
  { id: 30, name: "RTAB", main: false },
  { id: 31, name: "Nav2 Basics", main: false },
  { id: 32, name: "Nav Advanced", main: false },
];

export const links = [
  { source: 0, target: 1 },
  { source: 0, target: 2 },
  { source: 0, target: 14 },
  { source: 0, target: 15 },
  { source: 0, target: 16 },

  { source: 1, target: 3 },
  { source: 1, target: 5 },
  { source: 1, target: 18 },
  { source: 1, target: 19 },
  { source: 1, target: 20 },
  { source: 1, target: 21 },
  { source: 1, target: 22 },

  { source: 2, target: 17 },

  { source: 3, target: 23 },
  { source: 3, target: 24 },
  { source: 3, target: 25 },
  { source: 3, target: 26 },
  { source: 3, target: 27 },
  { source: 3, target: 28 },
  { source: 3, target: 29 },

  { source: 5, target: 30 },
  { source: 5, target: 31 },
  { source: 5, target: 32 },
];

export const descriptions = {
  0: "This section covers the foundations of robotics, AI, and their intersection.",
  1: "Introduction to basic ROS2 concepts and tutorials for beginners.",
  2: "A detailed overview of ROS basics and fundamental robotic concepts.",
  3: "Intermediate ROS2 topics, including advanced message passing and node interaction.",
  4: "Robotics theory involving kinematics, dynamics, and control systems.",
  5: "ROS2 Navigation and path-planning for autonomous robots.",
  6: "Manipulation of robotic arms and understanding the basics of robotic control.",
  7: "Creating your own robots with ROS2, including hardware and software integration.",
  8: "Artificial Intelligence and its applications in modern robotics.",
  9: "Debugging ROS2 programs and understanding error handling and troubleshooting.",
  10: "Product lifecycle course, from development to deployment in robotics.",
  11: "Web development skills specifically for robotics applications and control.",
  12: "Simulation environments for robotics, focusing on Gazebo and other tools.",
  13: "Enterprise-level robotics, scaling up solutions for industrial needs.",
  14: "Learning Python3 for robotics programming and integration with ROS.",
  15: "Linux commands and tools for robotics, including file handling, permissions, and scripting.",
  16: "C++ programming basics, including object-oriented concepts for writing efficient robotics code.",
  17: "Gazebo simulation with ROS2, focusing on environment creation, sensor integration, and robot control.",
  18: "TF (Transform) library in ROS2, used for tracking robot frames and transformations between coordinates.",
  19: "URDF (Unified Robot Description Format) for modeling robots in ROS2 and defining joint and link configurations.",
  20: "Learn ROS2 basics using Rust, a modern and safe systems programming language.",
  21: "ROS2 basics in 5 days with Python, offering a quick start guide for Python developers.",
  22: "ROS2 basics in 5 days with C++, providing a foundation for using ROS2 with C++ programming.",
  23: "ROS2 security concepts, focusing on secure communication, encryption, and authentication mechanisms.",
  24: "Migration guide from ROS1 to ROS2, covering differences, best practices, and migration strategies.",
  25: "Behavior Trees in ROS2 for structuring complex robotic behavior in an organized and modular way.",
  26: "Advanced modern C++ programming concepts applied to robotics, including memory management and concurrency.",
  27: "Intermediate ROS2 concepts with Python, diving into more advanced topics like action servers and services.",
  28: "Intermediate ROS2 with C++, covering more advanced topics such as message filters, action servers, and multithreading.",
  29: "ROS2 Control for managing hardware interfaces and controllers in robotic systems.",
  30: "RTAB (Real-Time Appearance-Based Mapping) for ROS2, focusing on SLAM (Simultaneous Localization and Mapping).",
  31: "Nav2 Basics in ROS2 for autonomous navigation, path planning, and obstacle avoidance.",
  32: "Advanced Navigation in ROS2, covering complex path-planning algorithms and multi-robot coordination.",
};
